src/Cituao/AcademicoBundle/Entity/Academico.php
<?php

namespace Cituao\AcademicoBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Filesystem\Filesystem;

/**
 * Cituao\AcademicoBundle\Entity\Academico
 *
 * @ORM\Table(name="Academico")
 * @ORM\Entity(repositoryClass="Cituao\AcademicoBundle\Entity\AcademicoRepository")
 */
class Academico
{

	 /**
	 * @ORM\Column(type="integer")
	 * @ORM\Id
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
    private $id;

     /**
     * @ORM\Column(type="string", length=50)
	 * @Assert\NotBlank(message="Es obligatorio!")
	 * @Assert\Regex(pattern="/\d/", match=false, message="Nombre inválido!")
     */
    private $nombres;

     /**
     * @ORM\Column(type="string", length=50)
	 * @Assert\NotBlank(message="Es obligatorio")
	 * @Assert\Regex(pattern="/\d/", match=false, message="Apellido inválido!")
     */
    private $apellidos;

     /**
     * @ORM\Column(type="string", length=12, unique=true)
	 * @Assert\NotBlank(message="Es obligatorio!")
	 * @Assert\Regex(pattern="/^\d+$/", match=true, message="Cédula inválida!")
     */
    private $ci;

     /**
     * @ORM\Column(type="string", length=15)
     */
    private $telefonoMovil;

     /**
     * @ORM\Column(type="string", length=15)
     */
    private $telefonoFijo;

     /**
     * @ORM\Column(type="string", length=50)
	 * @Assert\Email(message = "Email inválido!")
     */
    private $email;

     /**
     * @ORM\Column(type="string", length=50)
	 * @Assert\Email(message = "Email inválido!")
     */
    private $emailInstitucional;
	
    /**
     * @ORM\Column(type="string", length=30)
     */
    private $path;

    /**
     * @ORM\Column(type="text", length=500)
     */
    private $perfil;

	/**
	* @ORM\Column(type="string", length=1)
	*/
	private $categoria;
	
	/**
	* @ORM\Column(type="boolean")
	*/
	private $declaracion;

	/**
     * @Assert\File(maxSize="6000000")
     */
    private $file;	
	
    /**
	* @ORM\OneToMany(targetEntity="Cituao\CoordBundle\Practicante", mappedBy = "academico")	
	**/
	protected $practicantes;

    /**
	* @ORM\ManyToMany(targetEntity="Cituao\UsuarioBundle\Programa", inversedBy = "academicos")	
	**/
	protected $programas;

	public $activos;
	
	public function __construct()
    {
        
		$this->practicantes = new ArrayCollection();
		$this->programas = new ArrayCollection();
    }

	public function __toString(){

		return sprintf('%s %s',$this->nombres, $this->apellidos);

	}
	
    /**
     * Get id
     *
     * @return integer 	
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nombres
     *
     * @param string $nombres
     * @return Academico
     */
    public function setNombres($nombres)
    {
        $this->nombres = $nombres;
    
        return $this;
    }

    /**
     * Get nombres
     *
     * @return string 
     */
    public function getNombres()
    {
        return $this->nombres;
    }

    /**
     * Set apellidos
     *
     * @param string $apellidos
     * @return Academico
     */
    public function setApellidos($apellidos)
    {
        $this->apellidos = $apellidos;
    
        return $this;
    }

    /**
     * Get apellidos
     *
     * @return string 
     */
    public function getApellidos()
    {
        return $this->apellidos;
    }

	/**
	 *
	 * nombre completo para los select 
	 */
	public function getNombreCompleto(){

		return sprintf('%s %s',$this->nombres, $this->apellidos);
	}


    /**
     * Set ci
     *
     * @param string $ci
     * @return Academico
     */
    public function setCi($ci)
    {
        $this->ci = $ci;
    
        return $this;
    }

    /**
     * Get ci
     *
     * @return string 
     */
    public function getCi()
    {
        return $this->ci;
    }

    /**
     * Set telefonoMovil
     *
     * @param string $telefonoMovil
     * @return Academico
     */
    public function setTelefonoMovil($telefonoMovil)
    {
        $this->telefonoMovil = $telefonoMovil;
    
        return $this;
    }

    /**
     * Get telefonoMovil
     *
     * @return string 
     */
    public function getTelefonoMovil()
    {
        return $this->telefonoMovil;
    }

    /**
     * Set telefonoFijo
     *
     * @param string $telefonoFijo
     * @return Academico
     */
    public function setTelefonoFijo($telefonoFijo)
    {
        $this->telefonoFijo = $telefonoFijo;
    
        return $this;
    }

    /**
     * Get telefonoFijo
     *
     * @return string 
     */
    public function getTelefonoFijo()
    {
        return $this->telefonoFijo;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return Academico
     */
    public function setEmail($email)
    {
        $this->email = $email;
    
        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmailInstitucional()
    {
        return $this->emailInstitucional;
    }

	    /**
     * Set email
     *
     * @param string $email
     * @return Academico
     */
    public function setEmailInstitucional($email)
    {
        $this->emailInstitucional = $email;
    
        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail()
    {
        return $this->email;
    }

	
    /**
     * Set perfil
     *
     * @param string $perfil
     * @return Academico
     */
    public function setPerfil($perfil)
    {
        $this->perfil = $perfil;
    
        return;
    }

    /**
     * Get perfil
     *
     * @return string 
     */
    public function getPerfil()
    {
        return $this->perfil;
    }

    /**
     * Set categoria
     *
     * @param string $categoria
     * @return Academico
     */
    public function setCategoria($categoria)
    {
        $this->categoria = $categoria;
    
        return;
    }

    /**
     * Get declaracion
     *
     * @return boolean 
     */
    public function getDeclaracion()
    {
        return $this->declaracion;
    }	
	
    /**
     * Set declaracion
     *
     * @param boolean $declaracion
     * @return Academico
     */
    public function setDeclaracion($declaracion)
    {
        $this->declaracion = $declaracion;
    
        return;
    }

    /**
     * Get categoria
     *
     * @return string 
     */
    public function getCategoria()
    {
        return $this->categoria;
    }	


    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;
    }

    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getFile()
    {
        return $this->file;
    }	
	
	
	
    /**
     * Set path
     *
     * @param string $path
     * @return Document
     */
    public function setPath($path)
    {
        $this->path = $path;
    
        return $this;
    }

    /**
     * Get path
     *
     * @return string 
     */
    public function getPath()
    {
        return $this->path;
    }



public function getAbsolutePath()
    {
        return null === $this->path
            ? null
            : $this->getUploadRootDir().'/'.$this->path;
    }

    public function getWebPath()
    {
        return null === $this->path
            ? null
            : $this->getUploadDir().'/'.$this->path;
    }

    protected function getUploadRootDir()
    {
        // the absolute directory path where uploaded
        // documents should be saved
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

    protected function getUploadDir()
    {
        // get rid of the __DIR__ so it doesn't screw up
        // when displaying uploaded doc/image in the view.
        return 'uploads/fotos';
    }


	public function upload()
	{
	 // the file property can be empty if the field is not required
		if (null === $this->getFile()) {
		    return;
		}

		// use the original file name here but you should
		// sanitize it at least to avoid any security issues

		// move takes the target directory and then the
		// target filename to move to
		
		/*if ($this->getPath() == $this->ci.'.png'){
			$fs = new Filesystem();
			$fs->remove($this->getUploadRootDir().'/'.$this->ci.'.png');
		} */	
		
		//asignamos la ci a la foto
		$nombre = $this->ci.'.png'; 
		$this->getFile()->move(
		    $this->getUploadRootDir(),
		    $nombre
		);
		//$this->getFile()->getClientOriginalName()
		
		
		
		// set the path property to the filename where you've saved the file
		//$this->path = $this->getFile()->getClientOriginalName();
		$this->path = $nombre;
		// clean up the file property as you won't need it anymore
		$this->file = null;	
	}
	
    /**
     * Add practicantes
     *
     * @param \Cituao\CoordBundle\Entity\Practicante $practicantes
     * @return Academico
     */
    public function addPracticante(\Cituao\CoordBundle\Entity\Practicante $practicantes)
    {
        $this->practicantes[] = $practicantes;
    
        return $this;
    }

    /**
     * Remove practicantes
     *
     * @param \Cituao\CoordBundle\Entity\Practicante $practicantes
     */
    public function removePracticante(\Cituao\CoordBundle\Entity\Practicante $practicantes)
    {
        $this->practicantes->removeElement($practicantes);
    }

    /**
     * Get practicantes
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getPracticantes()
    {
        return $this->practicantes;
    }

    /**
     * Add programas
     *
     * @param \Cituao\UsuarioBundle\Entity\Programa $programas
     * @return Academico
     */
    public function addPrograma(\Cituao\UsuarioBundle\Entity\Programa $programa)
    {
        $this->programas[] = $programa;
    
        return $this;
    }

    /**
     * Remove programas
     *

src/Cituao/AcademicoBundle/Resources/views/Default/academico.html.twig
{% extends 'CituaoAcademicoBundle::layout.html.twig' %}

{% block programa %}

{% endblock %}

{% block js  %}
<script>
$( "#asesoresInternos" ).css("background-color","#000");
$( "#asesoresInternos img" ).css("opacity","0.4");
$( "#asesoresInternos h3" ).css("opacity","0.4");
</script>

{% endblock %}


{% block content  %}
	{{ parent() }}
	<div class="content">
		{% block upSection  %}
		<div class = "upSection">
			<h1 class ="sectionTitle">Mis datos</h1>
			<a href="javascript:history.back()" class = "button"><img src="{{ asset('img/regresar.png') }}"/><h4>Regresar</h4></a>
		</div>
		{% endblock  %}

		{% block downSection  %}
		<div class="downSection">
			<div class="profileContainer">
				<div class="profilePictureContainer" style="width:200px;">
					<div class="imgContainer">
						<img class = "foto" border="0" src="{{ asset('uploads/fotos/' ~  academico.path) }}" alt="Pulpit rock" width="100%">
					</div>
				</div>
			<div class="profileFormContainer" style="height:580px;">
			<form action="{{ path('cituao_academico_actualizar', { 'ci': academico.ci }) }}" method="post" {{ form_enctype(formulario) }}>
			    <div>	{{ form_errors(formulario) }}	</div>

				
				
		
			    <div class="inputContainer"> 
					<h2>{{ form_label(formulario.nombres) }}</h2>
					<div class="input nomodificable">
					{{ form_errors(formulario.nombres) }}
					{{ form_widget(formulario.nombres, {'attr': {'class':'mediano'}} ) }}
					</div>
				</div>
			    <div class="inputContainer"> 
					<h2>{{ form_label(formulario.apellidos) }}</h2>
					<div class="input nomodificable">
					{{ form_errors(formulario.apellidos) }}
					{{ form_widget(formulario.apellidos, {'attr': {'class':'mediano'}} ) }}
					</div>
				</div>
					   <div class="inputContainer"> 
					<h2>{{ form_label(formulario.ci) }}</h2>
					<div class="input nomodificable">
					{{ form_errors(formulario.ci) }}
					{{ form_widget(formulario.ci, {'attr': {'class':'mediano'}} ) }}
					</div>
				</div>
			    <div class="inputContainer"> 
					<h2>{{ form_label(formulario.telefonoMovil) }}</h2>
					<div class="input nomodificable">
					{{ form_errors(formulario.telefonoMovil) }}
					{{ form_widget(formulario.telefonoMovil, {'attr': {'class':'corto'}} ) }}
					</div>
				</div>
			    <div class="inputContainer"> 
					<h2>{{ form_label(formulario.telefonoFijo) }}</h2>
					<div class="input nomodificable">
					{{ form_errors(formulario.telefonoFijo) }}
					{{ form_widget(formulario.telefonoFijo, {'attr': {'class':'corto'}} ) }}
					</div>
				</div>
			    <div class="inputContainer"> 
					<h2>{{ form_label(formulario.emailInstitucional) }}</h2>
					<div class="input nomodificable">
					{{ form_errors(formulario.emailInstitucional) }}
					{{ form_widget(formulario.emailInstitucional, {'attr': {'class':'mediano'}} ) }}
					</div>
			   </div>

			    <div class="inputContainer"> 
					<h2>{{ form_label(formulario.email) }}</h2>
					<div class="input nomodificable">
					{{ form_errors(formulario.email) }}
					{{ form_widget(formulario.email, {'attr': {'class':'mediano'}} ) }}
					</div>
			   </div>
				<div class="inputContainer"> 	
					<h2>{{ form_label(formulario.perfil) }}</h2>
					<div class="input nomodificable">
					{{ form_errors(formulario.perfil) }}
					{{ form_widget(formulario.perfil, {'attr': {'class':'mediano'}} ) }}
					</div>
				</div>
			   
			    {{ form_rest(formulario) }}
			     <div class="inputContainer" style="margin-top:80px; margin-left:-10px; width:auto !important">
			<div style="position:relative; float:right">
				<img style="position:absolute; left:15px; float:left; pointer-events:none;" src="{{ asset('img/guardar.png') }}" />
			    <input class="button" style="padding-left:38px"  type="submit" value="Guardar" />
			      </div>
			</div>
			  
			</form>	
		</div><!-- profileFormContainer -->
		</div><!-- profileContainer -->
		</div><!-- downSection -->
		{% endblock  %}
	</div><!-- content -->
{% endblock %}

src/Cituao/AcademicoBundle/Resources/views/Default/asesoria.html.twig
{% extends 'CituaoAcademicoBundle::layout.html.twig' %}

{% block programa %}
{{ programa.nombre }}
{% endblock %}

{% block js  %}
<script>
$( "#practicantes" ).css("background-color","#000");
$( "#practicantes img" ).css("opacity","0.4");
$( "#practicantes h3" ).css("opacity","0.4");
</script>

{% endblock %}

{% block content  %}
	<div class="content">
		<h2 id="titlee">Consultando la Asesoría # {{ datos.numase }}</h2>

		<div id = "menuop">
			<ul>
			<li><a href="javascript:history.back()" class = "baropcion">Regresar</a></li>
			</ul>
		</div>

	
	<form action="" method="post">
		<div>	
		<label>Asesor:</label>
		<textarea cols="125" rows="10" readonly>{{ datos.docase }}</textarea>
		</div>
		
		<div>	
		<label>Practicante:</label>
		<textarea cols="125" rows="10" readonly>{{ datos.docpra }}</textarea>
		</div>

	</form>	
	</div>
{% endblock %}

src/Cituao/AcademicoBundle/Resources/views/Default/centro.html.twig
{% extends 'CituaoAcademicoBundle::layout.html.twig' %}

{% block programa %}

{% endblock %}

{% block js  %}
<script>
$( "#asesoresInternos" ).css("background-color","#000");
$( "#asesoresInternos img" ).css("opacity","0.4");
$( "#asesoresInternos h3" ).css("opacity","0.4");
</script>

{% endblock %}
{% block content  %}
<div class="content">
	{% block upSection  %}
	<div class = "upSection">
		<h1 class ="sectionTitle">Centro de práctica</h1>
		<a href="javascript:history.back()" class = "button"><img src="{{ asset('img/regresar.png') }}"/><h4>Regresar</h4></a>
	</div>
	{% endblock  %}

	{% block downSection  %}
	<form action="" method="post">
		<div class = "downSection"> 
			<div class="profileContainer">
				<div class="profileFormContainer" style="height:580px;">
					<div class="inputContainer nomodificable">
						<h2>Nombre</h2>
						<div class="input nomodificable"  >
						<input type="text" value = "{{ centro.getNombre }}" readonly class = "largo" >
							</div>
					</div>

					<div class="inputContainer nomodificable">	
						<h2>Dirección</h2>
						<div class="input nomodificable" >
						<textarea style="border:none !important; font-family:helvetica;" cols="30" rows="2" readonly>{{ centro.direccion }}</textarea>
						</div>
					</div>

					<div class="inputContainer nomodificable">	
						<h2>Teléfono</h2>
						<div class="input nomodificable"  >
						<input type="text" value = "{{ centro.telefono }}" readonly>
							</div>
					</div>

					<div class="inputContainer nomodificable">	
						<h2>Teléfono fijo</h2>
						<div class="input nomodificable"  >
						<input type="text" value = "{{ centro.extension }}" readonly>
							</div>
					</div>

					<div class="inputContainer nomodificable">	
						<h2>Email</h2>
						<div class="input nomodificable"  >
						<input type="text" value = "{{ centro.email }}" readonly>
						</div>
					</div>

					<div class="inputContainer nomodificable">	
						<h2>Sitio web</h2>
						<div class="input nomodificable"  >
						<a href=  "{{ centro.url }}" >{{ centro.url }}</a>
							</div>
					</div>

				</form>	
			</div><!-- profileFormContainer -->
		</div><!-- profileContainer -->
	</div><!-- downSection -->
	{% endblock  %}
</div><!-- content -->
{% endblock %}

src/Cituao/AcademicoBundle/Resources/views/Default/externo.html.twig
{% extends 'CituaoAcademicoBundle::layout.html.twig' %}

{% block programa %}

{% endblock %}

{% block js  %}
<script>
$( "#asesoresInternos" ).css("background-color","#000");
$( "#asesoresInternos img" ).css("opacity","0.4");
$( "#asesoresInternos h3" ).css("opacity","0.4");
</script>

{% endblock %}

{% block content  %}
{{ parent() }}
<div class="content">
	{% block upSection  %}
	<div class = "upSection">
		<h1 class ="sectionTitle">Consulta de Asesor externo</h1>
		<a href="javascript:history.back()" class = "button"><img src="{{ asset('img/regresar.png') }}"/><h4>Regresar</h4></a>
	</div>
	{% endblock  %}

	{% block downSection  %}
	<div class = "downSection"> 
		<div class="profileContainer">
			<div class="profileFormContainer" style="height:580px;">
				<form action="" method="post">
					<div class="inputContainer">  
						<h2>Asesor:</h2>
						<div class="input nomodificable">
						<input type="text" value = "{{ externo.getNombreCompleto }}" readonly class = "largo">
						</div>

					</div>

					<div class="inputContainer">  	
						<h2>Teléfono movil:</h2>
						<div class="input nomodificable">
						<input type="text" value = "{{ externo.telefonoMovil }}" readonly>
						</div>

					</div>

					<div class="inputContainer">  	
						<h2>Teléfono fijo:</h2>
						<div class="input nomodificable">
						<input type="text" value = "{{ externo.telefonoFijo }}" readonly>
						</div>

					</div>

					<div class="inputContainer">  	
						<h2>Email:</h2>
						<div class="input nomodificable">
						<input type="text" value = "{{ externo.email }}" readonly>
						</div>

					</div>

					<div class="inputContainer">  	
						<h2>Cargo:</h2>
						<div class="input nomodificable">
						<input type="text" value = "{{ externo.cargo }}" readonly>
						</div>

					</div>

				</form>	
				</div > <!-- profileFormContainer -->
			</div ><!-- profileContainer -->
			</div><!-- downSection -->
			{% endblock %}
			</div><!--content -->
			{% endblock %}

src/Cituao/AcademicoBundle/Resources/views/Default/formcomentario.html.twig
{% extends 'CituaoAcademicoBundle::layout.html.twig' %}

{% block programa %}
{{ programa.nombre }}
{% endblock %}

{% block infowrapper  %}
	<div id="infoWrapper">
		<h2 id="titlee">Registrando comentarios Evaluacion # {{ datos.numase }}</h2>

		<div id = "menuop">
			<ul>
			<li><a href="javascript:history.back()" class = "baropcion">Regresar</a></li>
			</ul>
		</div>

	
	<form action="{{ path('cituao_academico_registrar_asesoria'  , { 'id': datos.id, 'numase': datos.numase }) }}" method="post" {{ form_enctype(formulario) }}>
	    
					{{ form_errors(formulario) }}
				
					<div>
					{{ form_label(formulario.proceso) }}
					{{ form_widget(formulario.proceso) }}
					{{ form_errors(formulario.proceso) }}
					</div>
					<div>
					{{ form_label(formulario.herramientas) }}
					{{ form_widget(formulario.herramientas) }}
					{{ form_errors(formulario.herramientas) }}
					</div>
					
					{{ form_row(formulario.dl21) }}
					{{ form_row(formulario.dl22) }}
					{{ form_row(formulario.dl23) }}
					{{ form_row(formulario.dl24) }}
					{{ form_row(formulario.dl25) }}
					{{ form_row(formulario.dl26) }}
					{{ form_row(formulario.dl27) }}
					{{ form_row(formulario.dl28) }}
					{{ form_row(formulario.dl29) }}
				
					{{ form_row(formulario.va31) }}
					{{ form_row(formulario.va32) }}
					{{ form_row(formulario.va33) }}
					{{ form_row(formulario.va34) }}
					{{ form_row(formulario.va35) }}
					{{ form_row(formulario.va36) }}
					{{ form_row(formulario.va37) }}
					{{ form_row(formulario.va38) }}
					{{ form_row(formulario.va39) }}
					
					{{ form_row(formulario.comentarioExterno) }}
			
				
					{{ form_label(formulario.comentarioAcademico) }}
					{{ form_widget(formulario.comentarioAcademico) }}
					{{ form_errors(formulario.comentarioAcademico) }}
		
				
			{{ form_rest(formulario) }}
			<input class="boton" type="submit" value="Guardar" />
	</form>	
	</div>
{% endblock %}

src/Cituao/AcademicoBundle/Resources/views/Default/index.html.twig
{% extends 'CituaoAcademicoBundle::layout.html.twig' %}

{% block programa %}
{{ programa.nombre }}
{% endblock %}

{% block infowrapper  %}
	<div id="infoWrapper">
		<h2 id="titlee">
			PANEL<span>PRINCIPAL ACADÉMICO<span> 
		</h2>
		<div id="buttonsContainer">	
			<a href="{{ path('cituao_academico_practicantes') }}" class="button" id="practicantes"> 
				<h2>MIS PRACTICANTES</h2>
				<img id="practicanteIcon" src="{{ asset('img/practicanteIcon.png') }}">
			</a>
			<a href="{{ path('cituao_academico_actualizar') }}" class="button"  id="asesoresExternos">
				<h2>MIS DATOS<span> </span></h2>
				<img id="externoIcon" src="{{ asset('img/externoIcon.png') }}">
			</a>
		</div>
	</div><!-- infowrapper -->
{% endblock %}

src/Cituao/AcademicoBundle/Resources/views/Default/practicantes.html.twig
{% extends 'CituaoAcademicoBundle::layout.html.twig' %}
{% block programa %}

{% endblock %}

{% block js  %}
	<script>
	$( "#practicantes" ).css("background-color","#000");
	$( "#practicantes img" ).css("opacity","0.4");
	$( "#practicantes h3" ).css("opacity","0.4");

	$(document).ready(function() {
		setTimeout(function() {
			$("#info").fadeOut(1500);
		},3000);
	});
	</script>
{% endblock %}

{% block content  %}
	{{ parent() }}
	<div class="content">
		{% block upSection  %}
		<div class = "upSection">
			<h1 class ="sectionTitle">Mis Practicantes son ({{ datos.numeroPracticantes }}) </h1>
			<!--<a href="javascript:history.back()" class = "button"><img src="{{ asset('img/regresar.png') }}"/><h4>Regresar</h4></a>-->	
		</div>
		{% endblock  %}

		{% block downSection  %}
			<div class = "downSection">
				{% if msgerr.id == '1' %}
					<div id = "error">{{ msgerr.descripcion }} </div>		
				{% else %}
					<table class="practicantesTableHead">
						<tbody>
							<tr class="tableHead">
								<th width="5%"></th>
								<th width="6%"></th>
								<th width="19%"></th>
								<th width="10%"></th>
								<th width="28%"><img style="margin-left:70px;" src="{{ asset('img/mailLabel.png') }}"/></th>
								<th width="11%"><img style="margin-left:20px;" src="{{ asset('img/telefonoLabel.png') }}"/></th>
								<th><h3><span>Asesor externo</span></h3></th>
								<th></th>
							</tr> <!--tablehead -->
						</tbody>
					</table><!-- practicantes tableHead -->
					
					{% set id = 1 %}
					<div style="width: 100%; height: 750px; overflow: auto; position:relative; padding-bottom:30px;">
						<div style="width: 100%; height: 25px; overflow: auto; position:relative">
						<div id = "info" style="width: 100%; height: 20px; overflow: auto; position:relative; color:#2E8B57">
						{% for flashMessage in app.session.flashbag.get('info') %}
						    <h4 id="msginfo">{{ flashMessage }}</h4>
						{% endfor %}
						</div> <!-- div flash bag -->
						</div>
						<table class = "practicantesTable">
							<tbody>
								<tr class="spacer"></tr>
								{% for practicante in listaPracticantes %}
								<tr height="20px"  class="tableItem">
									<td id="hoverDiv">

										<td><h2>{{ id }}</h2></th>
											<td height="20px">
												<div class="itemImgContainer">
													<img class = "foto" border="0" src="{{ asset('uploads/fotos/' ~  practicante.path) }}" alt="Foto" width="100%">
												</div>
											</td>
											<td>{{ practicante.nombres }}</td>						
											<td>{{ practicante.apellidos }}</td>
											<td>{{ practicante.emailInstitucional }} </br>
												{{ practicante.emailPersonal }}
											</td>
											
											<td>{{ practicante.telefonoMovil }}</td>
											<td><a href="{{ path('cituao_academico_verasesorexterno', { 'id': practicante.externo.id}) }}">{{ practicante.externo.nombreCompleto }}</a></td>
											<td><a href="{{ path('cituao_academico_vercentro', { 'id': practicante.centro.id}) }}">{{ practicante.centro.nombre }}</a></td>
											<td>
												<table class="opciones">
													<td>
														<a href="{{ path('cituao_academico_cronograma', { 'id': practicante.id}) }}"><img src="{{ asset('img/cronograma.png') }}" ><h3> Cronograma </h3></a>
													</td>
												</table> <!-- opciones -->
											</td>

										</td><!-- hoverDiv -->
									</tr><!-- tableItem -->
									{% set id = id + 1 %}
									<tr class="spacer"></tr>
									
									{% endfor %}
									<tr class="spacer"></tr>
									<tr class="spacer"></tr>
									<tr class="spacer"></tr>
									<tr class="spacer"></tr>
									<tr class="spacer"></tr>
								</tbody>
							</table>
						</div><!-- scroll Div-->	
				{% endif %}
		</div><!-- downSection-->
		{% endblock %}
	</div> <!-- cierra info wrapper-->

	<script>
	$( ".tableItem" ).mouseenter(function() {
		var hoverDiv = $('#hoverDiv', this);
		var opciones = $('.opciones', this);
		var itemPicture = $('.itemImgContainer', this);
		$(hoverDiv).css("background-color","#ec1c24");
		$(itemPicture).css("border-color","#ec1c24");

		$( opciones).animate({
			opacity: 1,
			top: "-4px",
		}, 300, function() {
	    // Animation complete.
	});
	});

	$( ".tableItem" ).mouseleave(function() {
		var hoverDiv = $('#hoverDiv', this);
		var itemPicture = $('.itemImgContainer', this);
		var opciones = $('.opciones', this);
		$(hoverDiv).css("background-color","#fff");
		$(itemPicture).css("border-color","#242021");
		$( opciones).animate({
			opacity: 0,
			top: "26px",
		}, 300, function() {
	    // Animation complete.
	});
	});
	</script>
{% endblock %}